#!/bin/bash

############################
## GENERATED BY tunextflow {{SCRIPT_VERSION}}
## at {{EXECUTION_DATE}}
############################

## before script
{{BEFORE_SCRIPT}}
## module load
{{MODULE_LOAD}}
## check run_dir
[[ {{RUN_DIR}} ]] cd {{RUN_DIR}}
## 
set +e
nextflow run {{CONFIG_COMMAND_LINE}} {{LIB_COMMAND_LINE}} {{PARAM_COMMAND_LINE}} {{PROJECT_DIR}}
{{AFTER_SCRIPT}}